### PR TITLE
Fixes #1313

### LINKED ISSUE #1313: Global Longest Flowpath sometimes not returned in downloaded reports
See [Elevation Comparison.xlsx](https://doimspp-my.sharepoint.com/:x:/g/personal/kkolb_usgs_gov/EYiCaqCDICJOrSTS4CqVdVYB6B0owgex31ruWojDAjB0Wg?e=qfppAd&ovuser=0693b5ba-4b18-4d7b-9341-f32f400a5494%2Camedenblik%40usgs.gov&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjA0MDExMTQxMyJ9)

- [x] 1. The global longest flowpath is not returned in the downloaded report when you download the report immediately. This is a timing issue. Possible fix: put a loader on the Download button so the user cannot download the report before everything is ready. Kitty and Pete M have more information on this issue.

- [x] 2. Also, automatically turn on the longestflowpath3d layer when it is available on the map.
[image](https://user-images.githubusercontent.com/40237491/169091220-71e2432f-a9e6-49a5-be68-7a46f1decc4d.png)
- [x] 3. The longest flow path doesnt show up in the legend of the report map unless the report is opened after the longestflow path is returned.

Tickets:
https://streamstats.freshdesk.com/a/tickets/116426

### PR DESCRIPTION
**Pull request by harper-wavra**
- Shows longest flow path layer automatically on the main map if returned from the services.
- Added loader and disabled download button until longest flow path is downloaded
- Fixed bug that was causing the longest flow path layers to not show up as options in the report map legend if report was opened before longest flow path was done downloading 

Can get testing points from the Elevation Comparision.xlsx Pete sent us a couple weeks ago.

### CODE REVIEW

**Comment by amedenblik** [comment]
@harper-wavra There are some merge conflicts

**Comment by harper-wavra** [comment]
@amedenblik should be good to review now.

**Review by amedenblik — CHANGES_REQUESTED** [review]
- [x] Potential bug found by testing with this point: 44.89774, -93.14793. Delineated and only selected the LFPLENGTH basin characteristic. longestflowpath was added to the legend but not turned on by default.

**Comment by harper-wavra** [comment]
Now it checks for both `longestflowpath3d` and  `longestflowpath`

**Review by amedenblik — APPROVED** [review]

**Pull request merged**
