### PR TITLE
Highlight values in culvert report that don't meet SCS standards

### LINKED ISSUE #1295: Add highlighting for values not meeting SCS
Gardner will populate a column with values for standards in the data dictionary.

### PR DESCRIPTION
**Pull request by Abigail770**

### CODE REVIEW

**Review by amedenblik — COMMENTED** [review]
Not sure if this is related to this PR, but should Habitat Quality Score appear as NaN?
image

**Comment by Abigail770** [comment]
Habitat Quality Score showing as NaN is fixed.  I changed the data type from short int to string for both that and Roadway Classification in this pull request (both are actually text fields and were showing as NaN).

**Comment by harper-wavra** [comment]
It is working well for me. I could see needing a message stating what the highlighting means, maybe in the disclaimer section? I think we could merge for now though to get it on the dev site.

**Review by harper-wavra — APPROVED** [review]

**Review by amedenblik — CHANGES_REQUESTED** [review]
Agree with Harper! @Abigail770 can you please add a quick sentence, maybe to the end of this disclaimer, to describe what the highlights mean?
image

**Review by amedenblik — APPROVED** [review]

**Pull request merged**
