### PR TITLE
Fixes #1944 - adds separate color for each subbasin

### LINKED ISSUE #1944: Use multiple colors for line delineation sub-basins
Cooperator would like each sub-basin to have a different color

Use something like ColorBrewer to select 508-compliant colors

https://colorbrewer2.org/
https://davidmathlogic.com/colorblind

### PR DESCRIPTION
**Pull request by harper-wavra**

### CODE REVIEW

**Review by amedenblik — COMMENTED** [review]
- [x] It is working for sure, but I noticed that these colors are pretty similar (especially the right 2 basins):
image

I wonder if we should shuffle the colors a little bit, so that the adjacent basins are a bit more visually distinct from each other? 

- [x] Should we also edit the symbology (add the colors) to the final report map?

**Review by amedenblik — COMMENTED** [review]
The changes to symbology are looking good! 

I did notice that duplicate requests are being made to https://test.streamstats.usgs.gov/streamstatsservices/watershed.geojson?. For example, I made a line with two intersection points. The first point had one request to the watershed.geojson endpoint, but the second point had 3 identical requests to watershed.geojson. I'm not sure when this started happening, but it seems to be slowing things down.

**Comment by harper-wavra** [comment]
mmm that's strange, not noticing this on my end. Were they all type 'xhr'? 
[two points](https://github.com/USGS-WiM/StreamStats/assets/59063181/bc358a3c-c817-4573-b522-58d8a7eac8f4)
[three points](https://github.com/USGS-WiM/StreamStats/assets/59063181/ce822916-bc4f-482d-a95e-a26f14e6e7fb)

**Review by amedenblik — APPROVED** [review]
I am not seeing that issue anymore! Not sure what happened. Will redeploy now.

**Comment by amedenblik** [comment]
Deployed to https://dev.streamstats.usgs.gov/sc-runoff/

**Pull request merged**
