### PR TITLE
Fixes #1503 URL parameter to open a gage page 

### LINKED ISSUE #1503: URL parameter to open a gage page
It would be nice if there was a URL parameter that automatically opened to a specific gage page.

### PR DESCRIPTION
**Pull request by amedenblik**
Closes #1503 

Created #1909 to open a specific tab, because the gageplots branch does not yet have the URL parameter capabilities pulled in

I went ahead and worked on this issue to support FloodWIDE capabilities

### CODE REVIEW

**Review by harper-wavra — APPROVED** [review]
Working well, just noticed a couple of things, though feel free to merge & we can make a separate issue for these 

- If the gage doesn't exist the gage page just appears empty, we should have a warning or something and close the page
- After I close the gage page the url params don't go away

**Comment by amedenblik** [comment]
Made these changes:

- If you close the gage page, the url parameters are cleared
- If you click a gage on the map and open the gage page, the url parameters are added
- If you enter an invalid gage number, the gage page closes, an error toast appears, and the url parameters are removed
     - To prevent the gage page error toast from being immediately closed by the PROSPER loading toast, I made a small change in the PropserService

One issue that remains: if you close the modal with the Escape key, the URL parameters are not cleared. This is also an issue for the BP modal. Do you know how to fix this?

**Review by harper-wavra — APPROVED** [review]
Working well 👍 

I wasn't even aware you could close the modals with 'esc'. This might be a little hacky, but you could wait for a keypress of 'esc' then call that close function.

**Comment by amedenblik** [comment]
Made these changes:

- Clicking outside the BP modal no longer closes the BP modal
- Pressing the esc key in the BP modal and gage page modal now clears the URL parameters

**Review by harper-wavra — APPROVED** [review]

**Pull request merged**
