### PR TITLE
CS-1387: Added ability to download Synthetic Hydrograph results as CSV File

### PR DESCRIPTION
**Pull request by KipSullivan**
- After result tables are calculated, the 'Download CSV' button appears at the bottom of the dialog page, allowing the user to download the results as a csv file

### CODE REVIEW

**Review by amedenblik — CHANGES_REQUESTED** [review]
Works well! A few comments:

- [x] If there are no warning messages, omit the line about warning messages in the CSV. We didn't have this implemented for the "USGS SC Flood Hydrograph for Urban Watersheds" tab, since that model will always at least one warning message.
- [x] There are some funny symbols in the CSV (all the column headers on this row)
image
- [x] Add a title line for each table in the CSV: Watershed Data, Unit Hydrograph Data, Runoff Results, Critical Durations, and D-Hour Storm Hydrograph Ordinates
image

**Comment by harper-wavra** [comment]
There are some funny symbols in the results as well. It looks like the symbol for "hrs" is not getting translated correctly. 
image

**Comment by harper-wavra** [comment]
I can work on these updates today.

**Review by amedenblik — APPROVED** [review]
Your changes look good! Can you review my change (fixed typo and removed gamma symbol, at least for now)?

**Review by harper-wavra — APPROVED** [review]

**Pull request merged**
