### PR TITLE
Fixes 1594: Add batch status tab

### LINKED ISSUE #1594: BP: Create batch status tab
Part of #1455 

Create the content for the "Batch Status" tab:

- [x] Upon initial load, make a GET request to the BatchProcessor (https://streamstats.usgs.gov/batchprocessor) /status/ endpoint-- this will return an array of Status IDs and their associated status Message. Save that for later (see below).
- [x] Add a text box that says "Email Address:"
- [x] When the user enters their email address, make a GET request to the BatchProcessor (https://streamstats.usgs.gov/batchprocessor) /batch/ endpoint (example: `/batch/?emailAddress=amedenblik%40usgs.gov`)
     - Example response:
 ```
[
  {
    "ID": 42,
    "Region": "NC",
    "BasinCharacteristics": [
      ""
    ],
    "FlowStatistics": [
      ""
    ],
    "LocalIDField": "localID",
    "GeometryFilename": "smbatch.zip",
    "EmailAddress": "amedenblik@usgs.gov",
    "NumberPoints": 1,
    "TimeSubmitted": "2023-02-10T16:01:07.507658",
    "TimeStarted": null,
    "TimeCompleted": null,
    "StatusID": 1,
    "InputCRS": "2264",
    "OutputCRS": "2264",
    "Order": 42,
    "NumberPointsSuccessful": null,
    "ResultsURL": null,
    "points": [
      {
        "ID": 75,
        "BatchID": 42,
        "Latitude": 36.3006745521288,
        "Longitude": -79.5456896692051,
        "LocalID": "pointA",
        "StatusID": 1,
        "SnappedLatitude": null,
        "SnappedLongitude": null,
        "WorkspaceID": null
      }
    ]
  },
  {
    "ID": 43,
    "Region": "NC",
    "BasinCharacteristics": [
      ""
    ],
    "FlowStatistics": [
      ""
    ],
    "LocalIDField": "localID",
    "GeometryFilename": "smbatch.zip",
    "EmailAddress": "amedenblik@usgs.gov",
    "NumberPoints": 1,
    "TimeSubmitted": "2023-02-10T16:01:28.771983",
    "TimeStarted": null,
    "TimeCompleted": null,
    "StatusID": 1,
    "InputCRS": "2264",
    "OutputCRS": "2264",
    "Order": 43,
    "NumberPointsSuccessful": null,
    "ResultsURL": null,
    "points": [
      {
        "ID": 76,
        "BatchID": 43,
        "Latitude": 36.3006745521288,
        "Longitude": -79.5456896692051,
        "LocalID": "pointA",
        "StatusID": 1,
        "SnappedLatitude": null,
        "SnappedLongitude": null,
        "WorkspaceID": null
      }
    ]
  },
  {
    "ID": 44,
    "Region": "NC",
    "BasinCharacteristics": [],
    "FlowStatistics": [],
    "LocalIDField": "localID",
    "GeometryFilename": "smbatch.zip",
    "EmailAddress": "amedenblik@usgs.gov",
    "NumberPoints": 1,
    "TimeSubmitted": "2023-02-10T16:01:42.683336",
    "TimeStarted": null,
    "TimeCompleted": null,
    "StatusID": 1,
    "InputCRS": "2264",
    "OutputCRS": "2264",
    "Order": 44,
    "NumberPointsSuccessful": null,
    "ResultsURL": null,
    "points": [
      {
        "ID": 77,
        "BatchID": 44,
        "Latitude": 36.3006745521288,
        "Longitude": -79.5456896692051,
        "LocalID": "pointA",
        "StatusID": 1,
        "SnappedLatitude": null,
        "SnappedLongitude": null,
        "WorkspaceID": null
      }
    ]
  },
  {
    "ID": 36,
    "Region": "NC",
    "BasinCharacteristics": [
      "DRNAREA",
      "PCTREG1",
      "PCTREG2",
      "PCTREG3",
      "PCTREG4",
      "PCTREG5",
      "I24H50Y",
      "LC06DEV",
      "LC06IMP",
      "LC11IMP"
    ],
    "FlowStatistics": [
      "2",
      "31"
    ],
    "LocalIDField": "localID",
    "GeometryFilename": "smbatch.zip",
    "EmailAddress": "amedenblik@usgs.gov",
    "NumberPoints": 1,
    "TimeSubmitted": "2023-02-09T20:18:46.645550",
    "TimeStarted": "2023-02-09T20:45:23.913851",
    "TimeCompleted": "2023-02-09T20:45:43.495713",
    "StatusID": 3,
    "InputCRS": "2264",
    "OutputCRS": "2264",
    "Order": 36,
    "NumberPointsSuccessful": null,
    "ResultsURL": null,
    "points": [
      {
        "ID": 67,
        "BatchID": 36,
        "Latitude": 36.3006745521288,
        "Longitude": -79.5456896692051,
        "LocalID": "pointA",
        "StatusID": 3,
        "SnappedLatitude": 36.3006745521288,
        "SnappedLongitude": -79.5456896692051,
        "WorkspaceID": "NC20230210012047341000"
      }
    ]
  }
]
```
- [x] After the GET request is returned, populate a table that shows the batch status. It should include these columns (shown here is what we want the column header to be, and what the content should be):
     - [x] "Batch ID": BatchID field
     - [x] "Status": Each batch will have a StatusID field, which is a number. Translate this to the associated status Message, described above. For example, a batch with StatusID of 3 should show "Complete: Successful" in the table.
     - [x] "Time Submitted": TimeSubmitted field 
     - [x] "Time Started": TimeStarted field (if it is null, make it appear blank)
     - [x] "Time Completed": TimeCompleted field (if it is null, make it appear blank)
     - [x] "Results": ResultsURL in the form of a hyperlink (if it is null, make it appear as blank)
     - [x] "State/Region": Region field
     - [x] "Number Points Requested": NumberPoints field
     - [x] "Number Points Successful": NumberPointsSuccessful field (if it is null, make it appear as blank)
- [x] Provide some user instructions at the top of the tab.
- [x] At the end of each row, add a trash can icon. (The trash can icon will be dealt with in #1630)

### PR DESCRIPTION
**Pull request by alaws-USGS**
Closes #1594

### CODE REVIEW

**Review by harper-wavra — COMMENTED** [review]
This looks great, very exciting!! 

- When I first click on Batch Status there is spinning loader that displays. I don't think we need a loader until after a user enters an email and it is retrieving information. 
- Maybe we could have the email textbox and the check status button on the same line.
- If there are no results for a certain email, could we display a message maybe "No batches returned for the entered email." instead of an empty table?

**Review by amedenblik — CHANGES_REQUESTED** [review]
I have the same feedback as Harper!

One other thing: when I highlight the text in the email address box, the modal closes. Is there a way to fix this?

**Comment by amedenblik** [comment]
Also just FYI the S3 links are no longer working for some reason, but it's not your fault. The bucket went missing on S3.

**Comment by alaws-USGS** [comment]
Requested updates: 

- [x] Spinning loader after submit is clicked
- [x] Email textbox and button on same line
- [x] Display a message "No batches returned for the entered email" when nothing returned
- [x]  When text is highlighted in the email address box, the modal closes. Is there a way to fix this?

**Comment by alaws-USGS** [comment]
@amedenblik this appears to be an issue with the underlying bootstrap version https://github.com/twbs/bootstrap/issues/36745

When I click and drag but stay within the modal, the modal window does not collapse.

**Review by amedenblik — CHANGES_REQUESTED** [review]
Changes look good! Can we actually put the Email address text, input box, and button on the same line? You may need to fiddle with the HTML/CSS to add some extra space between the input box and button and make it so they are aligned nicely 

Quick Powerpoint mockup:
image

**Review by amedenblik — APPROVED** [review]
Thanks for making the changes!

**Review by harper-wavra — APPROVED** [review]
Nice work!

**Comment by harper-wavra** [comment]
Dev site updated: https://dev.streamstats.usgs.gov/bp/.

**Pull request merged**
