### PR TITLE
Fixes #1418 - Remove references to legacy real-time gage pages

### LINKED ISSUE #1418: Remove references to legacy real-time gage pages
Legacy real-time gage pages will be decommissioned in July 2023. We should remove any references to the legacy pages:

image

image

### PR DESCRIPTION
**Pull request by amedenblik**
Closes #1418

### CODE REVIEW

**Comment by harper-wavra** [comment]
Do you think we need to change the link that says "NWIS Page" to "Waterdata Page"?
image

**Comment by amedenblik** [comment]
@USGSPMM3 What do you think about Harper's question?

**Comment by HansVraga** [comment]
I've reached out to the wdfn folks - we'll get the answer there.

**Comment by HansVraga** [comment]
I don't want this word from the wdfn team to hold us up too much. Maybe `station page` for now since we have the station type listed?

**Comment by harper-wavra** [comment]
We should call them `Monitoring Location Page's`

**Review by harper-wavra — APPROVED** [review]

**Pull request merged**
