### PR TITLE
Fixes #1831 Show non-simplified basins when edited

### LINKED ISSUE #1831: Show non-simplified basins when edited
Per Pete M, when the user edits a basin, the simplified basin is shown. We should show the non-simplified basin. 

I have not confirmed this functionality.

### PR DESCRIPTION
**Pull request by amedenblik**
Closes #1831 

- After you edit a basin, the basin is no longer simplified.
- When you click "Edit Basin", the simplified basin disappears and the nonsimplified basin is used for the rest of the workflow.

Testing point: 33.90056, -80.16623 in SC

### CODE REVIEW

**Comment by harper-wavra** [comment]
Turning to draft status until we get more information from Pete at the Kitchen Sink check-in.

**Review by harper-wavra — CHANGES_REQUESTED** [review]
- [x] After you select edit basin the legend gets a bit messed up. It shows that the Basin Boundary is checked, and the Non-Simplified Basin is unchecked, I think it should be the other way around. 
- [x] In the report it is showing the simplified basin boundary, not sure if that is the excepted outcome.

**Comment by amedenblik** [comment]
Changes made: 

-  After you click Edit Bain, the Basin Boundary is now unchecked and removed from the map, and the Non-Simplified Basin is checked and added to the map
- After you have submitted an edited basin, the non-simplified basin is no longer available on the map/legend
- In the map report, the non-simplified basin boundary is displayed, in red

**Review by harper-wavra — APPROVED** [review]
This is working really well!

**Comment by amedenblik** [comment]
Deployed to https://dev.streamstats.usgs.gov/ss

**Pull request merged**
