### PR TITLE
fixed broken links in sidebar

### PR DESCRIPTION
**Pull request by lujoh**
Fixed links in sidebar that were giving me a 404 not found error.

### CODE REVIEW

**Comment by amedenblik** [comment]
Thanks, Lucia, for fixing these broken links! For approval, please update the [ChangeLog](https://github.com/lujoh/StreamStats/blob/dev/CHANGELOG.md)-- please add a note about what you fixed under "Unreleased" > "Fixed". 

We also created an issue for the StreamStats Information Portal, which is unfortunately an internal-only repository. Thanks for letting us know!

**Review by amedenblik — CHANGES_REQUESTED** [review]
Thanks, Lucia, for fixing these broken links! For approval, please update the [ChangeLog](https://github.com/lujoh/StreamStats/blob/dev/CHANGELOG.md)-- please add a note about what you fixed under "Unreleased" > "Fixed".

We also created an issue for the StreamStats Information Portal, which is unfortunately an internal-only repository. Thanks for letting us know!

**Comment by lujoh** [comment]
Thank you for your reply Andrea. I have added my changes to the ChangeLog.

**Review by amedenblik — APPROVED** [review]

**Comment by amedenblik** [comment]
Thanks! This change will likely be pushed to our public website during our next update on February 9.

**Pull request merged**
