### PR TITLE
update data dictionary with new fields and citations

### PR DESCRIPTION
**Pull request by Abigail770**

### CODE REVIEW

**Review by amedenblik — CHANGES_REQUESTED** [review]
- [x] Citations are not formatted well in some sections
Example of citations that aren't formatted well:
image
Example of citations that are formatted well:
image

- [x] Site Information Citations section is blank. Is this information forthcoming or unavailable for certain sites? 
image

I wasn't able to attend the last meeting-- apologies if these things were discussed!

**Comment by Abigail770** [comment]
Site Information citation just added by Gardner.  The citations in blue are formatted as links since hyperlinks were provided.  The other citations didn't have hyperlinks provided which is which I formatted them as regular text.  Is there a certain formatting StreamStats uses when links aren't provided?

**Comment by amedenblik** [comment]
It seems like those citations do have URLs provided? For example, the last citation: 
image

The corresponding URL is https://dx.doi.org/10.3133/sir20135155

**Comment by Abigail770** [comment]
You're right! I was going off of the hyperlinks in the [excel sheet](https://doimspp.sharepoint.com/:x:/r/sites/GS-UMidWIM/_layouts/15/Doc.aspx?sourcedoc=%7BDF3D6F26-0278-48BA-8729-35A1CCE8E4F7%7D&file=MA_Statewide_Hydraulic_Model_StreamStats_Data_Dictionary.xlsx&action=default&mobileredirect=true), but I realize now they're the same as the links in the citations.

**Review by amedenblik — APPROVED** [review]
Looking good!

**Pull request merged**
